// Generated by https://quicktype.io

export interface Data {
  data: SchoolCenterForm;
}

export interface SchoolCenterForm {
  id:                   number;
  name:                 string;
  infraestructure_code: string;
  status:               number;
}
